# Generated by Django 5.2.1 on 2025-07-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.ImageField(upload_to='')),
                ('description', models.CharField(max_length=1000)),
                ('sort_description', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
    ]
